import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Heart, Lock, Mail, Stethoscope, User } from 'lucide-react';
import { supabase } from '../../lib/supabase';

export default function RegisterPage() {
  const navigate = useNavigate();
  const [role, setRole] = useState<'patient' | 'doctor' | null>(null);
  const [formData, setFormData] = useState({ fullName: '', email: '', password: '' });
  const submit = async (e: React.FormEvent) => { e.preventDefault(); if (!role) return; const { data } = await supabase.auth.signUp({ email: formData.email, password: formData.password, options: { data: { full_name: formData.fullName, role }, emailRedirectTo: `${window.location.origin}/login` } }); navigate(data.session ? (role === 'doctor' ? '/doctor/dashboard' : '/patient/dashboard') : '/login'); };
  if (!role) return <div className="min-h-[calc(100vh-64px)] flex items-center justify-center p-4"><div className="max-w-lg w-full bg-white rounded-3xl shadow-xl p-8 border"><Heart className="text-primary-600 mx-auto" /><h1 className="text-3xl font-black text-center mt-3 mb-8">Choose account type</h1><button onClick={() => setRole('patient')} className="w-full p-5 border-2 rounded-2xl text-left mb-4 flex gap-4"><User className="text-primary-600" /><span><b>Patient</b><br />Upload reports and book doctors</span></button><button onClick={() => setRole('doctor')} className="w-full p-5 border-2 rounded-2xl text-left flex gap-4"><Stethoscope className="text-primary-600" /><span><b>Doctor</b><br />Manage reports and appointments</span></button></div></div>;
  return <div className="min-h-[calc(100vh-64px)] flex items-center justify-center p-4"><form onSubmit={submit} className="max-w-md w-full bg-white rounded-3xl shadow-xl p-8 border space-y-5"><h1 className="text-3xl font-black text-center">Create {role} account</h1><label className="block"><span className="font-bold text-sm">Full Name</span><input required value={formData.fullName} onChange={(e) => setFormData({ ...formData, fullName: e.target.value })} className="mt-2 w-full p-3 border-2 rounded-xl" /></label><label className="block"><span className="font-bold text-sm">Email</span><div className="relative mt-2"><Mail className="absolute left-3 top-3 text-gray-400" /><input type="email" required value={formData.email} onChange={(e) => setFormData({ ...formData, email: e.target.value })} className="w-full pl-11 py-3 border-2 rounded-xl" /></div></label><label className="block"><span className="font-bold text-sm">Password</span><div className="relative mt-2"><Lock className="absolute left-3 top-3 text-gray-400" /><input type="password" required value={formData.password} onChange={(e) => setFormData({ ...formData, password: e.target.value })} className="w-full pl-11 py-3 border-2 rounded-xl" /></div></label><button className="w-full py-4 bg-primary-600 text-white rounded-2xl font-black">Register</button><p className="text-center text-sm"><Link to="/login" className="text-primary-600 font-black">Back to login</Link></p></form></div>;
}
