import { Link } from 'react-router-dom';
import { ArrowRight, Brain, Calendar, FileText, Heart, Search, Shield, Star, Stethoscope, Upload, Users } from 'lucide-react';

export default function LandingPage() {
  const features = [
    { icon: Upload, title: 'Upload Reports', text: 'Store blood tests, prescriptions, scans, and lab reports.' },
    { icon: Brain, title: 'AI Analysis', text: 'Get patient-friendly summaries with next-step guidance.' },
    { icon: Search, title: 'Find Doctors', text: 'Search specialists and book appointments.' },
  ];
  return <div><section className="min-h-[88vh] bg-gradient-to-br from-primary-50 via-white to-secondary-50 flex items-center"><div className="max-w-7xl mx-auto px-4 py-20 grid lg:grid-cols-2 gap-12 items-center"><div><span className="inline-flex items-center gap-2 px-4 py-2 bg-primary-100 text-primary-700 rounded-full font-bold text-sm"><Heart className="w-4 h-4" /> IASO Med</span><h1 className="mt-6 text-5xl lg:text-6xl font-black text-gray-900 leading-tight">Understand medical reports in seconds.</h1><p className="mt-6 text-lg text-gray-600 max-w-xl">A full healthcare workflow for patients and doctors: report upload, AI insights, doctor search, appointments, and clinical dashboards.</p><div className="mt-8 flex gap-4"><Link to="/register" className="px-8 py-4 bg-primary-600 text-white rounded-2xl font-black flex items-center gap-2">Get Started <ArrowRight /></Link><Link to="/login" className="px-8 py-4 bg-white border-2 border-gray-200 rounded-2xl font-black">Sign In</Link></div></div><div className="bg-white rounded-3xl shadow-2xl p-8 border"><div className="flex items-center gap-3 mb-6"><FileText className="text-primary-600" /><div><p className="font-black">Blood Panel Analysis</p><p className="text-sm text-gray-500">Status: normal</p></div></div><div className="grid grid-cols-3 gap-3 mb-6">{['Hemoglobin','Glucose','Cholesterol'].map((x) => <div className="bg-gray-50 p-4 rounded-2xl text-center" key={x}><p className="text-xs text-gray-500">{x}</p><p className="font-black">Normal</p></div>)}</div><p className="p-4 bg-primary-50 rounded-2xl text-gray-700">AI summary: Most values are healthy. Discuss cholesterol trends with a clinician.</p></div></div></section><section id="features" className="py-24 bg-white"><div className="max-w-7xl mx-auto px-4"><h2 className="text-4xl font-black text-center mb-12">Built for healthcare workflows</h2><div className="grid md:grid-cols-3 gap-8">{features.map((f) => <div key={f.title} className="p-8 rounded-3xl border bg-gray-50"><f.icon className="w-10 h-10 text-primary-600 mb-4" /><h3 className="font-black text-xl mb-2">{f.title}</h3><p className="text-gray-600">{f.text}</p></div>)}</div></div></section><section className="py-16 bg-primary-600 text-white"><div className="max-w-7xl mx-auto px-4 grid md:grid-cols-4 gap-6 text-center">{[[Users,'Patients'],[Stethoscope,'Doctors'],[Calendar,'Appointments'],[Shield,'Secure']].map(([Icon,label]: any) => <div key={label}><Icon className="mx-auto mb-2" /><p className="font-black text-2xl">{label}</p><p className="text-primary-100">Ready</p></div>)}</div></section><section className="py-20 text-center"><Star className="mx-auto text-amber-400 fill-amber-400" /><h2 className="text-3xl font-black mt-4 mb-6">Launch IASO Med today</h2><Link to="/register" className="px-8 py-4 bg-primary-600 text-white rounded-2xl font-black">Create account</Link></section></div>;
}
